// Generated by LiveScript 1.2.0
(function(){
  module.exports = function(config){
    return config.set({
      basePath: '../',
      files: ['vendor/scripts/jquery/jquery.js', 'vendor/scripts/angular/angular.js', 'vendor/scripts/angular-*/angular-*.js', '_public/js/app.js', '_public/**/*.html', '_public/*.html', 'test/unit/**/test_*.ls'],
      frameworks: ['jasmine'],
      exclude: [],
      logLevel: config.LOG_INFO,
      autoWatch: true,
      reporters: ['progress', 'junit'],
      junitReporter: {
        outputFile: 'test/test-results.xml'
      },
      port: 3334,
      runnerPort: 9100,
      browsers: ["Chrome"],
      captureTimeout: 5000,
      colors: true,
      singleRun: false,
      urlRoot: '/__karma/',
      preprocessors: {
        '**/*.html': 'html2js',
        '**/*.ls': 'Live'
      }
    });
  };
}).call(this);
